// @ts-nocheck
export default [
  () => import("@shikijs/langs/javascript"),
  () => import("@shikijs/langs/css"),
  () => import("@shikijs/langs/md"),
  () => import("@shikijs/langs/yaml"),
  () => import("@shikijs/langs/ts"),
  () => import("@shikijs/langs/sh"),
  () => import("@shikijs/langs/html"),
  () => import("@shikijs/langs/json"),
  () => import("@shikijs/langs/python"),
  () => import("@shikijs/langs/sql"),
  () => import("@shikijs/langs/bash"),
  () => import("@shikijs/langs/c"),
  () => import("@shikijs/langs/rust"),
  () => import("@shikijs/langs/markdown"),
  () => import("@shikijs/langs/java"),
  () => import("@shikijs/langs/php"),
  () => import("@shikijs/langs/go"),
  () => import("@shikijs/langs/shell"),
  () => import("@shikijs/langs/docker"),
  () => import("@shikijs/langs/dockerfile"),
  () => import("@shikijs/langs/vue"),
  () => import("@shikijs/langs/vue-directives"),
  () => import("@shikijs/langs/vue-html"),
  () => import("@shikijs/langs/vue-sfc-style-variable-injection"),
];
